### ISSUE TITLE
ChirpPlugin error(204): CHIRP_PLUGIN_UNKNOWN_ERROR

### ISSUE THREAD

**Issue by James-deWitt** [AlexanderKub/unity-chirp-plugin#6] opened 2019-04-03 02:31 UTC
I followed the updated readme instruction in a clean unity porject and InitSDK now works, but now when I press the StartSDK button I get the following error

> ChirpPlugin error(204): CHIRP_PLUGIN_UNKNOWN_ERROR

which is super weird since that's not one of the listed [chirp error codes](https://developers.chirp.io/docs/using-chirp/errors)

I don't know if it will help me much, but can I ask what version of Unity you are using for this?

**Comment by AlexanderKub** [comment] 2019-04-04 15:48
> I followed the updated readme instruction in a clean unity porject and InitSDK now works, but now when I press the StartSDK button I get the following error
> 
> > ChirpPlugin error(204): CHIRP_PLUGIN_UNKNOWN_ERROR
> 
> which is super weird since that's not one of the listed [chirp error codes](https://developers.chirp.io/docs/using-chirp/errors)
> 
> I don't know if it will help me much, but can I ask what version of Unity you are using for this?

According to the documentation: 204 - Audio IO error.
In last SDK updates errors codes was edit and C# code can return the wrong error message.
I test it in Unity 2018.3.7 and 2018.3.1. Both the Android and iOS app work correctly.
Maybe the problem is in permissions, can I ask your device OS version?

**Comment by James-deWitt** [comment] 2019-04-10 22:53
Android 9.0

**Comment by AlexanderKub** [comment] 2019-04-11 08:31
> Android 9.0

Unfortunately, I haven't an Android device with >= 6.0 version for testing, maybe the problem in Runtime permissions requests [Permissions overview](https://developer.android.com/guide/topics/permissions/overview). Did you get a permissions request when start app or start SDK? If not, when I need some work on [Chirp doc](https://developers.chirp.io/docs/getting-started/android#runtime-permissions), it will take some time.

**Comment by James-deWitt** [comment] 2019-04-13 04:20
No permissions requests

Ive tried it and got the same issues with android devices running 7.1.1 and 8.1.0 and gotten the same issue

I also tried exporting the android project and adding the permissions to the manifest in android studio.

No luck unfortunately.

**Comment by AlexanderKub** [comment] 2019-04-13 12:56
Fixed in https://github.com/AlexanderKub/chirp-unity-plugin/commit/ad7278356a0d08af35626b5ece6abac5b0821e6a. Tested on Android 7.0 device.

**Closed as completed by AlexanderKub** 2019-04-13 12:56 UTC

**Comment by James-deWitt** [comment] 2019-04-16 18:00
Yep that was it. Cheers!
